language: node_js
sudo: false
node_js:
  - 6
rvm:
  - 2.2
before_script:
  - npm install -g free-programming-books-lint
  - gem install awesome_bot
script:
  - fpb-lint .
  - awesome_bot free-programming-books.md --allow-redirect
