language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot *.md

language: node_js
sudo: false
node_js:
  - 6
before_script:
  - npm install -g free-programming-books-lint
script: fpb-lint .
