language: shell
dist: xenial
os: linux

jobs:
  include:
    -
      language: node_js
      node_js:
        - 6
      before_script:
        - npm install -g free-programming-books-lint
      script:
        - fpb-lint .

    -
      language: ruby
      if: commit_message =~ /check_urls:/
      rvm: 2.4.1
      before_script:
        - gem install awesome_bot
      script:
        - FILENAME=$(echo $TRAVIS_COMMIT_MESSAGE | awk -F: '{print $2}')
        - echo $FILENAME
        - awesome_bot "$FILENAME" --allow-redirect --allow-dupe --skip-save-results
