language: node_js
sudo: false
node_js:
  - 6
before_script:
  - npm install -g free-programming-books-lint
script:
  - fpb-lint .

jobs:
  include:
    -
      if: commit_message =~ /check urls/
      rvm:
        - 2.2
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot free-programming-books.md --allow-redirect --allow-dupe --white-list web.archive.org
