name: Check URLs from changed files

on:
  push:
  pull_request:

permissions:
  # needed for checkout code
  contents: read

# This allows a subsequently queued workflow run to interrupt/wait for previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.run_id }}'
  cancel-in-progress: false  # true = interrupt, false = wait

jobs:

  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      fetch-depth: ${{ steps.set-params.outputs.fetch-depth }}
      files:       ${{ steps.set-files.outputs.files }}
      files-len:   ${{ steps.set-files.outputs.files-len }}
      matrix:      ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Determine workflow params
        id: set-params
        run: |
          echo "fetch_depth=0" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "fetch_depth=0" >> $GITHUB_OUTPUT
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ steps.set-params.outputs.fetch-depth }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.2
        with:
          separator: " "
          json: true
      - id: set-files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"  \
            | jq --raw-output '. | join(" ")'  \
            | sed -e 's/^/files=/'  \
            >> $GITHUB_OUTPUT
          echo "${{ steps.changed-files.outputs.all_changed_files }}"  \
            | jq --raw-output '. | length'  \
            | sed -e 's/^/files-len=/'  \
       
