name: free-programming-books-lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install -g free-programming-books-lint
    - run: |
        fpb-lint books casts courses more |& tee output.log
        result_code=${PIPESTATUS[0]}
        echo "::set-output name=fpb-lint::$(cat output.log)"
        gh pr review --body "The build failed with the following output:\n\`\`\`\n"$(cat output.log)\n\`\`\`"
        exit $result_code
